// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"time"
)

type TelegramSession struct {
	PhoneNumber string
	SessionData []byte
	CreatedAt   time.Time
}
